-- ==============================================================================
-- ROOTED™ (Le Benkeleng) Master Seed Dataset
-- Populates Lockers, Streetwear Labels, Master Catalog & Initial Test Orders
-- ==============================================================================

-- 1. LOCKER STATIONS
INSERT INTO public.locker_stations (id, name, address, hours, type, distance, city, commuter_tag)
VALUES ('loc-1', 'Diepkloof Zone 4 Spaza Hub', 'Mthembu Superette, 1248 Immink Dr, Diepkloof, Soweto', '07:00 – 21:00 Daily', 'Community Collection Counter', '0.6 km', 'Soweto', '🏪 Local Collection Hub • 🚕 Zone 4 Taxi Rank')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, address = EXCLUDED.address, hours = EXCLUDED.hours, commuter_tag = EXCLUDED.commuter_tag;
INSERT INTO public.locker_stations (id, name, address, hours, type, distance, city, commuter_tag)
VALUES ('loc-2', 'Braamfontein Juta Smart Locker', '68 Juta Street (Next to The Playground), Braamfontein', '24/7 Smart PIN Access', 'Automated Smart Locker', 'Central JHB', 'Johannesburg', '⚡ 24/7 Smart PIN • 🚆 350m Park Station')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, address = EXCLUDED.address, hours = EXCLUDED.hours, commuter_tag = EXCLUDED.commuter_tag;
INSERT INTO public.locker_stations (id, name, address, hours, type, distance, city, commuter_tag)
VALUES ('loc-3', 'Hatfield Plaza Smart Locker (012)', '1122 Burnett St, Hatfield, Pretoria (Near Gautrain)', '06:00 – 22:00 Mon-Sun', 'Pargo Campus Station', 'Pretoria East', 'Pretoria', '🎓 Hatfield Campus • 🚆 200m Gautrain Station')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, address = EXCLUDED.address, hours = EXCLUDED.hours, commuter_tag = EXCLUDED.commuter_tag;
INSERT INTO public.locker_stations (id, name, address, hours, type, distance, city, commuter_tag)
VALUES ('loc-4', 'Maponya Mall PEP Paxi Counter', 'Chris Hani Rd, Klipspruit, Soweto (Lower Level Entrance 3)', '09:00 – 18:00 Mon-Sun', 'PEP Paxi Hub', '1.4 km', 'Soweto', '📦 Dedicated Counter • 🚌 Central Bus Terminal')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, address = EXCLUDED.address, hours = EXCLUDED.hours, commuter_tag = EXCLUDED.commuter_tag;
INSERT INTO public.locker_stations (id, name, address, hours, type, distance, city, commuter_tag)
VALUES ('loc-5', 'Tembisa Plaza Pargo Hub', 'Shop 14, Andrew Mapheto Dr, Tembisa', '08:00 – 18:00 Daily', 'Pargo Collection Salon', 'East Rand', 'Gauteng East', '📍 Pargo Station • 🏬 Main Lower Plaza')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, address = EXCLUDED.address, hours = EXCLUDED.hours, commuter_tag = EXCLUDED.commuter_tag;
INSERT INTO public.locker_stations (id, name, address, hours, type, distance, city, commuter_tag)
VALUES ('loc-6', 'Umlazi Mega City Station', '50 Mangosuthu Hwy, Umlazi V, Durban', '08:30 – 17:30 Mon-Sun', 'Smart Locker Station', 'KZN South', 'Durban', '⚡ Smart Locker • 🚕 Mega City Rank 2')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, address = EXCLUDED.address, hours = EXCLUDED.hours, commuter_tag = EXCLUDED.commuter_tag;

-- 2. VENDORS / LABELS
INSERT INTO public.vendors (id, slug, name, letter, tagline, origin, city, gender, categories, price_range, featured, color, cover_image, product_count, coordinates, is_thrift, specialty, condition_standard, about_story, established_year, dispatch_hub, contact_phone, instagram, commission_rate)
VALUES (1, 'lesupa-atelier', 'Lesupa Atelier', 'L', 'Pretoria minimalist luxury, 280 GSM heavyweight tees & architectural embroidery', 'Arcadia / Hatfield, Pretoria', 'Pretoria', '{"UNISEX","MEN","WOMEN"}', '{"pretoria","outerwear","workwear","accessories"}', 'R 450 - R 1,400', true, '#C88A35', 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=1600&q=85', 42, '25.7479° S, 28.2293° E', false, 'High-GSM Combed Cotton & Minimalist Boxy Cut', '', 'Founded in Hatfield, Pretoria, Lesupa Atelier bridges Scandinavian architectural restraint with unapologetic South African street presence. Every garment is crafted from custom-milled 280 GSM ring-spun cotton with dropped shoulder seams and tone-on-tone embroidery, built for the discerning capital city tastemaker.', '2021', 'Pretoria Hatfield Hub (Bob Go Couriers)', '+27 12 345 6789', '', 0.13)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, tagline = EXCLUDED.tagline, cover_image = EXCLUDED.cover_image;
INSERT INTO public.vendors (id, slug, name, letter, tagline, origin, city, gender, categories, price_range, featured, color, cover_image, product_count, coordinates, is_thrift, specialty, condition_standard, about_story, established_year, dispatch_hub, contact_phone, instagram, commission_rate)
VALUES (2, 'mokasi', 'Mokasi Streetwear', 'M', 'Pretoria urban silhouettes, oversized double-knit tracksuits & bold streetwear prints', 'Mamelodi & Soshanguve, Pretoria', 'Pretoria', '{"UNISEX","MEN","WOMEN"}', '{"pretoria","outerwear"}', 'R 650 - R 1,650', true, '#111827', 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=1600&q=85', 38, '25.7069° S, 28.3275° E', false, 'Oversized Streetwear Cuts & Heavy Cotton Interlock', '', 'Born from the vibrant streets of Mamelodi and Soshanguve, Mokasi represents the raw, dynamic energy of Pretoria youth culture. Known for extreme volume through the sleeves, heavyweight 420 GSM double-knit tracksuits, and deep cultural graphics, Mokasi has become a hallmark of Pretoria streetwear pride.', '2019', 'Pretoria Central Distribution (Bob Go Couriers)', '+27 12 345 6789', '', 0.13)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, tagline = EXCLUDED.tagline, cover_image = EXCLUDED.cover_image;
INSERT INTO public.vendors (id, slug, name, letter, tagline, origin, city, gender, categories, price_range, featured, color, cover_image, product_count, coordinates, is_thrift, specialty, condition_standard, about_story, established_year, dispatch_hub, contact_phone, instagram, commission_rate)
VALUES (3, 'galxboy', 'Galxboy Heritage Drop', 'G', 'Pretoria''s pioneer streetwear legacy — iconic graphic silhouettes & statement headwear', 'Menlyn / Pretoria, 012', 'Pretoria', '{"UNISEX","MEN","WOMEN"}', '{"pretoria","accessories","outerwear"}', 'R 450 - R 1,950', true, '#C88A35', 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=1600&q=85', 56, '25.7825° S, 28.2755° E', false, 'Iconic SA Pop Culture & Heavy Melton Varsity Jackets', '', 'Starting as a humble T-shirt brand in Pretoria and evolving into a national cultural juggernaut, Galxboy paved the way for modern South African urban fashion. This curated heritage drop features premium varsity outerwear, heavyweight chenille patches, and archival collector items.', '2008', 'Menlyn Retail Logistics Hub', '+27 12 345 6789', '', 0.13)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, tagline = EXCLUDED.tagline, cover_image = EXCLUDED.cover_image;
INSERT INTO public.vendors (id, slug, name, letter, tagline, origin, city, gender, categories, price_range, featured, color, cover_image, product_count, coordinates, is_thrift, specialty, condition_standard, about_story, established_year, dispatch_hub, contact_phone, instagram, commission_rate)
VALUES (4, 'soweto-threads', 'Soweto Threads', 'S', 'Heritage raw selvage denim, chainstitched tailoring & formal pleats', 'Orlando West, Soweto', 'Soweto', '{"MEN","WOMEN","UNISEX"}', '{"workwear","outerwear"}', 'R 780 - R 1,800', true, '#1E3A8A', 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=1600&q=85', 48, '26.2415° S, 27.9157° E', false, '14oz Raw Red-Line Selvage Denim & Chainstitching', '', 'Handcrafted in an Orlando West studio just blocks from Vilakazi Street, Soweto Threads pays homage to historic township tailoring and the refined Swenka aesthetic. Utilizing Japanese shuttle-loom shuttle selvage denim, every jacket and trouser is built to develop a singular patina personal to the wearer.', '2018', 'Soweto Diepkloof Spaza Station (Bob Go)', '+27 12 345 6789', '', 0.13)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, tagline = EXCLUDED.tagline, cover_image = EXCLUDED.cover_image;
INSERT INTO public.vendors (id, slug, name, letter, tagline, origin, city, gender, categories, price_range, featured, color, cover_image, product_count, coordinates, is_thrift, specialty, condition_standard, about_story, established_year, dispatch_hub, contact_phone, instagram, commission_rate)
VALUES (5, 'braam-district', 'Braam District', 'B', '480 GSM heavy fleece & commuter technical silhouettes', 'Braamfontein, Johannesburg', 'Johannesburg', '{"UNISEX","MEN","WOMEN"}', '{"outerwear","accessories"}', 'R 520 - R 1,200', true, '#111827', 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=1600&q=85', 64, '26.1929° S, 28.0345° E', false, 'Heavy Cotton & Tactile Cargo Details', '', 'Braam District is the uniform of Johannesburg''s creative core. Designed steps from Park Station and the Nelson Mandela Bridge, their gear focuses on ultra-heavyweight 480 GSM French terry fleece, waterproof Cordura accessories, and thermal layering tailored for Highveld winters.', '2020', 'Braamfontein Juta Smart Locker', '+27 12 345 6789', '', 0.13)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, tagline = EXCLUDED.tagline, cover_image = EXCLUDED.cover_image;
INSERT INTO public.vendors (id, slug, name, letter, tagline, origin, city, gender, categories, price_range, featured, color, cover_image, product_count, coordinates, is_thrift, specialty, condition_standard, about_story, established_year, dispatch_hub, contact_phone, instagram, commission_rate)
VALUES (6, 'gusheshe-classics', 'Gusheshe Classics', 'G', 'Vulcanized footwear inspired by South African motorsport & spinning heritage', 'Pinetown, KwaZulu-Natal', 'Durban', '{"UNISEX","MEN"}', '{"kicks"}', 'R 1,450 - R 2,200', true, '#C88A35', 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1600&q=85', 32, '29.8167° S, 30.8500° E', false, 'Vulcanized Waffle Sole & Suede Motorsport Overlays', '', 'Engineered in Pinetown, KwaZulu-Natal, Gusheshe Classics translates South Africa''s legendary BMW E30 325i spinning and motorsport culture into vulcanized sneaker architecture. Featuring tire-tread gum rubber outsoles, reinforced double toe-caps, and memory foam insoles built for longevity.', '2022', 'Durban Central Pargo Station', '+27 12 345 6789', '', 0.13)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, tagline = EXCLUDED.tagline, cover_image = EXCLUDED.cover_image;
INSERT INTO public.vendors (id, slug, name, letter, tagline, origin, city, gender, categories, price_range, featured, color, cover_image, product_count, coordinates, is_thrift, specialty, condition_standard, about_story, established_year, dispatch_hub, contact_phone, instagram, commission_rate)
VALUES (7, 'dunusa-archive', 'Dunusa Archive Co.', 'D', 'Curated 1-of-1 90s sportswear, crinkle nylon windbreakers & motorsport track tops', 'Small Street CBD, Johannesburg', 'Johannesburg', '{"UNISEX","MEN","WOMEN"}', '{"thrift","outerwear"}', 'R 380 - R 890', true, '#059669', 'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=1600&q=85', 26, '26.2023° S, 28.0471° E', true, '90s Sportswear & Technical Windbreakers', 'Grade A+ Flawless Mint (Steam Cleaned)', 'Scouting daily across the labyrinthine wholesale bales of Small Street CBD, Dunusa Archive Co. hand-picks the rarest 1990s Italian and American technical windbreakers, racing jackets, and motorsport track tops. Every piece is triple steam-cleaned, measured to the centimeter, and guaranteed 1-of-1.', '2017', 'Johannesburg CBD Vault', '+27 12 345 6789', '', 0.13)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, tagline = EXCLUDED.tagline, cover_image = EXCLUDED.cover_image;
INSERT INTO public.vendors (id, slug, name, letter, tagline, origin, city, gender, categories, price_range, featured, color, cover_image, product_count, coordinates, is_thrift, specialty, condition_standard, about_story, established_year, dispatch_hub, contact_phone, instagram, commission_rate)
VALUES (8, 'kasi-vintage-vault', 'Kasi Vintage Vault', 'K', 'Sophiatown heavy leather flight jackets, vintage knit polos & pleated trousers', 'Diepkloof Zone 2, Soweto', 'Soweto', '{"MEN","UNISEX"}', '{"thrift","workwear","outerwear","accessories"}', 'R 380 - R 1,450', true, '#B45309', 'https://images.unsplash.com/photo-1520975954732-35dd22299614?auto=format&fit=crop&w=1600&q=85', 19, '26.2482° S, 27.9401° E', true, 'Heavy Leathers & 70s Sophiatown Knits', 'Grade A Mint (Conditioned Leather)', 'Preserving the legendary style of Sophiatown jazz pioneers and Soweto sartorialists, Kasi Vintage Vault unearths archival heavyweight shearling leather jackets, fine wool knits, and hand-tooled brass-buckle belts. Deeply conditioned with organic oils to last decades.', '2016', 'Diepkloof Zone 4 Spaza Hub', '+27 12 345 6789', '', 0.13)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, tagline = EXCLUDED.tagline, cover_image = EXCLUDED.cover_image;
INSERT INTO public.vendors (id, slug, name, letter, tagline, origin, city, gender, categories, price_range, featured, color, cover_image, product_count, coordinates, is_thrift, specialty, condition_standard, about_story, established_year, dispatch_hub, contact_phone, instagram, commission_rate)
VALUES (9, 'bree-st-reworks', 'Bree St. Reworks', 'B', '1-of-1 upcycled workwear vests, patched raw denim & commuter canvas gear', 'Bree Taxi Interchange, Johannesburg', 'Johannesburg', '{"UNISEX","MEN","WOMEN"}', '{"thrift","workwear"}', 'R 480 - R 920', true, '#4B5563', 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=1600&q=85', 22, '26.1989° S, 28.0380° E', true, 'Reworked Duck Canvas & Patchwork', 'Upcycled Heritage Grade (Triple Reinforced)', 'Situated at the pulsing heart of Johannesburg transit, Bree St. Reworks deconstructs decommissioned transit overalls, heavy duck canvas jackets, and mining uniforms into functional modern streetwear vests and carryalls with brass D-rings and industrial stitching.', '2021', 'Bree Taxi Interchange Station', '+27 12 345 6789', '', 0.13)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, tagline = EXCLUDED.tagline, cover_image = EXCLUDED.cover_image;
INSERT INTO public.vendors (id, slug, name, letter, tagline, origin, city, gender, categories, price_range, featured, color, cover_image, product_count, coordinates, is_thrift, specialty, condition_standard, about_story, established_year, dispatch_hub, contact_phone, instagram, commission_rate)
VALUES (10, 'south-beach-retro', 'South Beach Retro', 'S', 'Coastal 90s washed corduroy overshirts, graphic tees & vintage surf wear', 'The Workshop / South Beach, Durban', 'Durban', '{"UNISEX","MEN","WOMEN"}', '{"thrift","outerwear"}', 'R 350 - R 750', true, '#D97706', 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=1600&q=85', 17, '29.8587° S, 31.0218° E', true, 'Sun-Drenched Corduroys & 90s Graphic Tees', 'Grade A+ Vintage Mint (Pre-shrunk & Washed)', 'Curating sun-bleached coastal nostalgia from Durban''s surf arcades and beachfront bazaars. Specializing in washed 8-wale corduroy overshirts, rare vintage tour tees, and relaxed warm-climate layering.', '2019', 'Umlazi Mega City Station', '+27 12 345 6789', '', 0.13)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, tagline = EXCLUDED.tagline, cover_image = EXCLUDED.cover_image;
INSERT INTO public.vendors (id, slug, name, letter, tagline, origin, city, gender, categories, price_range, featured, color, cover_image, product_count, coordinates, is_thrift, specialty, condition_standard, about_story, established_year, dispatch_hub, contact_phone, instagram, commission_rate)
VALUES (11, 'urban-soul', 'Urban Soul', 'U', 'Pretoria streetwear crafted from garage cuts to capital culture', 'Pretoria, South Africa', 'Pretoria', '{"UNISEX","MEN","WOMEN"}', '{"outerwear","workwear","accessories","pretoria"}', 'R 320 - R 849', true, '#d6a34c', 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=1600&q=85', 36, '25.7461° S, 28.1881° E', false, '420 GSM Boxy Hoodies & Heavyweight Cargo Twill', '', 'Thabo started Urban Soul in his mother''s garage, cutting his first run of ten hoodies for friends at TUT. He wanted streetwear that felt like Pretoria, not a copy of something overseas.', '2023', 'Pretoria Central Depot (Bob Go Couriers)', '+27 71 832 9481', '@urbansoul_pta', 0.08)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, tagline = EXCLUDED.tagline, cover_image = EXCLUDED.cover_image;

-- 3. PRODUCTS
INSERT INTO public.products (id, title, brand, brand_slug, category, city, gender, price, original_price, image, secondary_image, badge, origin, fabric, sizes, description, is_new, is_sale, is_thrift, is_pretoria, condition, measurements, rarity, stock, stock_per_size, status)
VALUES (1, 'Lesupa 280 GSM Boxy Heavyweight Tee', 'Lesupa Atelier', 'lesupa-atelier', 'pretoria', 'Pretoria', '{"UNISEX","MEN","WOMEN"}', 620, 750, 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80', 'PRETORIA 012', 'Arcadia, Pretoria', '280 GSM Combed Ring-Spun Cotton', '{"S","M","L","XL"}', 'Architecturally cut with a high ribbed collar, dropped shoulder seams, and subtle tone-on-tone embroidery. Designed for the modern South African streetwear enthusiast.', true, false, false, true, NULL, NULL, NULL, 24, '{"S":5,"M":8,"L":7,"XL":4}'::jsonb, 'active')
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price, stock = EXCLUDED.stock, status = EXCLUDED.status;
INSERT INTO public.products (id, title, brand, brand_slug, category, city, gender, price, original_price, image, secondary_image, badge, origin, fabric, sizes, description, is_new, is_sale, is_thrift, is_pretoria, condition, measurements, rarity, stock, stock_per_size, status)
VALUES (2, 'Mokasi Pitori Signature Oversized Tracksuit', 'Mokasi Streetwear', 'mokasi', 'pretoria', 'Pretoria', '{"UNISEX","MEN"}', 1450, 1750, 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?auto=format&fit=crop&w=900&q=80', 'PRETORIA CUT', 'Mamelodi, Pretoria', '420 GSM Double-Knit Cotton Interlock', '{"M","L","XL"}', 'Cut with extreme volume through the sleeve and stacked hem trousers. Embroidered with Mokasi''s signature brand stamp in antique ochre thread.', true, false, false, true, NULL, NULL, NULL, 14, '{"M":4,"L":6,"XL":4}'::jsonb, 'active')
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price, stock = EXCLUDED.stock, status = EXCLUDED.status;
INSERT INTO public.products (id, title, brand, brand_slug, category, city, gender, price, original_price, image, secondary_image, badge, origin, fabric, sizes, description, is_new, is_sale, is_thrift, is_pretoria, condition, measurements, rarity, stock, stock_per_size, status)
VALUES (3, 'Galxboy Heritage 2008 Varsity Jacket', 'Galxboy Heritage Drop', 'galxboy', 'pretoria', 'Pretoria', '{"UNISEX","MEN","WOMEN"}', 1850, NULL, 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=900&q=80', 'HERITAGE ARCHIVE', 'Menlyn, Pretoria', 'Heavy Melton Wool & Contrast Vegan Leather Sleeves', '{"S","M","L","XL"}', 'An archival tribute to Pretoria''s greatest streetwear pioneer. Heavyweight chenille patch branding with ribbed striped trim.', false, false, false, true, NULL, NULL, NULL, 8, '{"S":2,"M":2,"L":3,"XL":1}'::jsonb, 'active')
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price, stock = EXCLUDED.stock, status = EXCLUDED.status;
INSERT INTO public.products (id, title, brand, brand_slug, category, city, gender, price, original_price, image, secondary_image, badge, origin, fabric, sizes, description, is_new, is_sale, is_thrift, is_pretoria, condition, measurements, rarity, stock, stock_per_size, status)
VALUES (4, 'Soweto Raw Selvage Denim Jacket', 'Soweto Threads', 'soweto-threads', 'workwear', 'Soweto', '{"MEN","UNISEX"}', 1280, 1450, 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=900&q=80', 'SOWETO CUT', 'Orlando West, Soweto', '14oz Unwashed Red-Line Selvage Denim', '{"S","M","L","XL"}', 'Handcrafted in Orlando West using Japanese shuttle-loom shuttle selvage. Unwashed, deep indigo with copper hardware that patinas uniquely over time.', true, false, false, false, NULL, NULL, NULL, 12, '{"S":3,"M":4,"L":3,"XL":2}'::jsonb, 'active')
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price, stock = EXCLUDED.stock, status = EXCLUDED.status;
INSERT INTO public.products (id, title, brand, brand_slug, category, city, gender, price, original_price, image, secondary_image, badge, origin, fabric, sizes, description, is_new, is_sale, is_thrift, is_pretoria, condition, measurements, rarity, stock, stock_per_size, status)
VALUES (5, 'Braam 480 GSM Thermal Fleece Hoodie', 'Braam District', 'braam-district', 'outerwear', 'Johannesburg', '{"UNISEX","MEN","WOMEN"}', 890, NULL, 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=900&q=80', 'BRAAM EXCLUSIVE', 'Braamfontein, JHB', '480 GSM Heavy French Terry Cotton', '{"XS","S","M","L","XL"}', 'Cut with a boxy, dropped-shoulder silhouette built for chilly Highveld evenings and early morning metro commutes.', true, false, false, false, NULL, NULL, NULL, 18, '{"XS":2,"S":4,"M":6,"L":4,"XL":2}'::jsonb, 'active')
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price, stock = EXCLUDED.stock, status = EXCLUDED.status;
INSERT INTO public.products (id, title, brand, brand_slug, category, city, gender, price, original_price, image, secondary_image, badge, origin, fabric, sizes, description, is_new, is_sale, is_thrift, is_pretoria, condition, measurements, rarity, stock, stock_per_size, status)
VALUES (6, 'Gusheshe Low-Top 325i Vulcanized Sneakers', 'Gusheshe Classics', 'gusheshe-classics', 'kicks', 'Durban', '{"UNISEX","MEN"}', 1650, 1950, 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=900&q=80', 'SPINNING HERITAGE', 'Pinetown, KZN', 'Full-Grain Cowhide Leather & High-Density Vulcanized Waffle Rubber', '{"UK 6","UK 7","UK 8","UK 9","UK 10","UK 11"}', 'Inspired by South Africa''s motorsport culture. Double-stitched toe cap, custom tire-tread outsole, and memory-foam insole.', false, true, false, false, NULL, NULL, NULL, 16, '{"UK 6":2,"UK 7":3,"UK 8":4,"UK 9":4,"UK 10":2,"UK 11":1}'::jsonb, 'active')
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price, stock = EXCLUDED.stock, status = EXCLUDED.status;
INSERT INTO public.products (id, title, brand, brand_slug, category, city, gender, price, original_price, image, secondary_image, badge, origin, fabric, sizes, description, is_new, is_sale, is_thrift, is_pretoria, condition, measurements, rarity, stock, stock_per_size, status)
VALUES (7, '90s Italian Colorblock Retro Windbreaker', 'Dunusa Archive Co.', 'dunusa-archive', 'thrift', 'Johannesburg', '{"UNISEX"}', 480, 650, 'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=900&q=80', '1-OF-1 VINTAGE', 'Small Street CBD, JHB', 'Crinkle Taslan Nylon & Mesh Lining', '{"L (Boxy 90s Fit)"}', 'Hand-picked from Small Street CBD wholesale stashes. Vibrant turquoise and cadmium orange blocking with brass YKK pulls. Steam-cleaned & sanitized.', false, false, true, false, '★ Grade A+ Flawless Mint', 'Pit-to-Pit: 62cm | Length: 70cm | Raglan Sleeve', 'Unique Single Item', 1, '{"L (Boxy 90s Fit)":1}'::jsonb, 'active')
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price, stock = EXCLUDED.stock, status = EXCLUDED.status;
INSERT INTO public.products (id, title, brand, brand_slug, category, city, gender, price, original_price, image, secondary_image, badge, origin, fabric, sizes, description, is_new, is_sale, is_thrift, is_pretoria, condition, measurements, rarity, stock, stock_per_size, status)
VALUES (8, 'Archival Sophiatown Leather Flight Bomber', 'Kasi Vintage Vault', 'kasi-vintage-vault', 'thrift', 'Soweto', '{"MEN","UNISEX"}', 1350, 1800, 'https://images.unsplash.com/photo-1520975954732-35dd22299614?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=80', '1-OF-1 VINTAGE', 'Diepkloof Zone 2, Soweto', 'Heavy Aniline Calfskin Leather & Quilted Lining', '{"XL (Tailored Boxy Fit)"}', 'Authentic Sophiatown jazz-era silhouette. Deep aged espresso patina with original shearling collar and heavy Talon zipper. Triple conditioned.', false, false, true, false, '★ Grade A (Rich Natural Patina)', 'Pit-to-Pit: 64cm | Shoulder: 52cm | Length: 68cm', 'Unique Single Item', 1, '{"XL (Tailored Boxy Fit)":1}'::jsonb, 'active')
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price, stock = EXCLUDED.stock, status = EXCLUDED.status;
INSERT INTO public.products (id, title, brand, brand_slug, category, city, gender, price, original_price, image, secondary_image, badge, origin, fabric, sizes, description, is_new, is_sale, is_thrift, is_pretoria, condition, measurements, rarity, stock, stock_per_size, status)
VALUES (9, 'Reworked Duck Canvas Commuter Vest', 'Bree St. Reworks', 'bree-st-reworks', 'thrift', 'Johannesburg', '{"UNISEX","MEN","WOMEN"}', 820, NULL, 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=900&q=80', '1-OF-1 VINTAGE', 'Bree Taxi Interchange, JHB', '16oz Repurposed Carhartt Duck Canvas', '{"M / L Adjustable"}', 'Reconstructed from decommissioned South African transit overalls and workwear jackets. Multi-pocket commuter layout with brass D-rings.', false, false, true, false, '★ Upcycled Grade (Triple Stitched)', 'Pit-to-Pit: 58cm | Length: 64cm', 'Unique Single Item', 1, '{"M / L Adjustable":1}'::jsonb, 'active')
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price, stock = EXCLUDED.stock, status = EXCLUDED.status;
INSERT INTO public.products (id, title, brand, brand_slug, category, city, gender, price, original_price, image, secondary_image, badge, origin, fabric, sizes, description, is_new, is_sale, is_thrift, is_pretoria, condition, measurements, rarity, stock, stock_per_size, status)
VALUES (10, '1994 Durban Surf Corduroy Overshirt', 'South Beach Retro', 'south-beach-retro', 'thrift', 'Durban', '{"UNISEX","MEN","WOMEN"}', 420, 550, 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80', '1-OF-1 VINTAGE', 'South Beach, Durban', '100% Cotton 8-Wale Vintage Corduroy', '{"L (Relaxed Fit)"}', 'Sun-drenched honey corduroy from Durban''s 90s coastal surf era. Features tortoise-shell buttons and dual flap pockets. Sanitized and steam-ironed.', false, false, true, false, '★ Grade A+ Mint', 'Pit-to-Pit: 60cm | Shoulder: 49cm | Length: 74cm', 'Unique Single Item', 1, '{"L (Relaxed Fit)":1}'::jsonb, 'active')
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price, stock = EXCLUDED.stock, status = EXCLUDED.status;
INSERT INTO public.products (id, title, brand, brand_slug, category, city, gender, price, original_price, image, secondary_image, badge, origin, fabric, sizes, description, is_new, is_sale, is_thrift, is_pretoria, condition, measurements, rarity, stock, stock_per_size, status)
VALUES (11, 'Vintage Highveld Racing Team Track Top', 'Dunusa Archive Co.', 'dunusa-archive', 'thrift', 'Johannesburg', '{"UNISEX"}', 560, NULL, 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=900&q=80', '1-OF-1 VINTAGE', 'Small Street CBD, JHB', 'Brushed Tricot Poly-Cotton Blend', '{"M (Slim Vintage Track Cut)"}', 'Sourced from a private collector in Turffontein. Embroidered chest insignia with gold piping along the raglan sleeves. Mint original condition.', false, false, true, false, '★ Grade A+ Mint', 'Pit-to-Pit: 54cm | Length: 67cm', 'Unique Single Item', 1, '{"M (Slim Vintage Track Cut)":1}'::jsonb, 'active')
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price, stock = EXCLUDED.stock, status = EXCLUDED.status;
INSERT INTO public.products (id, title, brand, brand_slug, category, city, gender, price, original_price, image, secondary_image, badge, origin, fabric, sizes, description, is_new, is_sale, is_thrift, is_pretoria, condition, measurements, rarity, stock, stock_per_size, status)
VALUES (12, 'Soweto Double-Pleated Tailored Chinos', 'Soweto Threads', 'soweto-threads', 'workwear', 'Soweto', '{"MEN","UNISEX"}', 950, 1100, 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=900&q=80', 'TAILORED FORMAL', 'Orlando West, Soweto', '100% Heavy Twill Cotton (320 GSM)', '{"30","32","34","36"}', 'Engineered with deep double front pleats, high-rise waistband with side tab adjusters, and a clean tapered break.', false, false, false, false, NULL, NULL, NULL, 14, '{"30":3,"32":5,"34":4,"36":2}'::jsonb, 'active')
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price, stock = EXCLUDED.stock, status = EXCLUDED.status;
INSERT INTO public.products (id, title, brand, brand_slug, category, city, gender, price, original_price, image, secondary_image, badge, origin, fabric, sizes, description, is_new, is_sale, is_thrift, is_pretoria, condition, measurements, rarity, stock, stock_per_size, status)
VALUES (13, 'Lesupa Minimalist Commuter Waxed Tote', 'Lesupa Atelier', 'lesupa-atelier', 'accessories', 'Pretoria', '{"UNISEX"}', 450, NULL, 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80', 'PRETORIA 012', 'Hatfield, Pretoria', '16oz Waxed Canvas & Full Grain Leather Handles', '{"One Size (18L)"}', 'Clean architectural carryall engineered for laptop commuting between Hatfield, Menlyn, and Johannesburg. Weather-resistant finish.', false, false, false, true, NULL, NULL, NULL, 9, '{"One Size (18L)":9}'::jsonb, 'active')
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price, stock = EXCLUDED.stock, status = EXCLUDED.status;
INSERT INTO public.products (id, title, brand, brand_slug, category, city, gender, price, original_price, image, secondary_image, badge, origin, fabric, sizes, description, is_new, is_sale, is_thrift, is_pretoria, condition, measurements, rarity, stock, stock_per_size, status)
VALUES (14, 'Braam Tactical Crossbody Messenger', 'Braam District', 'braam-district', 'accessories', 'Johannesburg', '{"UNISEX"}', 520, NULL, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=900&q=80', 'COMMUTER GEAR', 'Braamfontein, JHB', '1000D Ballistic Cordura Nylon & Fidlock Magnetic Buckle', '{"One Size (5L)"}', 'Built for hands-free mobility across the Nelson Mandela Bridge and MetroRail carriages. Rapid magnetic release clasp.', false, false, false, false, NULL, NULL, NULL, 11, '{"One Size (5L)":11}'::jsonb, 'active')
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price, stock = EXCLUDED.stock, status = EXCLUDED.status;
INSERT INTO public.products (id, title, brand, brand_slug, category, city, gender, price, original_price, image, secondary_image, badge, origin, fabric, sizes, description, is_new, is_sale, is_thrift, is_pretoria, condition, measurements, rarity, stock, stock_per_size, status)
VALUES (15, 'Kasi Archive Hand-Tooled Leather Belt', 'Kasi Vintage Vault', 'kasi-vintage-vault', 'accessories', 'Soweto', '{"MEN","UNISEX"}', 380, NULL, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1520975954732-35dd22299614?auto=format&fit=crop&w=900&q=80', 'SOLID BRASS', 'Diepkloof, Soweto', 'Vegetable-Tanned Saddle Leather & Solid Brass Hardware', '{"32","34","36","38"}', 'Hand-burnished edges with custom brass buckle. Built to last a lifetime, softening with every wear.', false, false, false, false, NULL, NULL, NULL, 8, '{"32":2,"34":3,"36":2,"38":1}'::jsonb, 'active')
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price, stock = EXCLUDED.stock, status = EXCLUDED.status;
INSERT INTO public.products (id, title, brand, brand_slug, category, city, gender, price, original_price, image, secondary_image, badge, origin, fabric, sizes, description, is_new, is_sale, is_thrift, is_pretoria, condition, measurements, rarity, stock, stock_per_size, status)
VALUES (16, 'Gusheshe Suede Track High-Tops', 'Gusheshe Classics', 'gusheshe-classics', 'kicks', 'Durban', '{"UNISEX","MEN"}', 1890, 2200, 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=80', 'LIMITED RUN', 'Pinetown, KZN', 'Perforated Suede, Padded Collar & Gum Rubber Outsole', '{"UK 7","UK 8","UK 9","UK 10"}', 'High-top ankle support built with reinforced heel counter and authentic motorsport race striping.', false, true, false, false, NULL, NULL, NULL, 7, '{"UK 7":1,"UK 8":3,"UK 9":2,"UK 10":1}'::jsonb, 'active')
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price, stock = EXCLUDED.stock, status = EXCLUDED.status;
INSERT INTO public.products (id, title, brand, brand_slug, category, city, gender, price, original_price, image, secondary_image, badge, origin, fabric, sizes, description, is_new, is_sale, is_thrift, is_pretoria, condition, measurements, rarity, stock, stock_per_size, status)
VALUES (101, 'Urban Soul 420 GSM Oversized Hoodie', 'Urban Soul', 'urban-soul', 'outerwear', 'Pretoria', '{"UNISEX"}', 699, 799, 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?auto=format&fit=crop&w=900&q=80', 'BEST SELLER', 'Pretoria, South Africa', '420 GSM Brushed French Terry Cotton, Double-Lined Hood', '{"S","M","L","XL"}', 'Signature boxy silhouette with dropped shoulders and thick ribbed cuffs. Developed in Pretoria.', true, false, false, true, NULL, NULL, NULL, 92, '{"S":18,"M":34,"L":28,"XL":12}'::jsonb, 'active')
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price, stock = EXCLUDED.stock, status = EXCLUDED.status;
INSERT INTO public.products (id, title, brand, brand_slug, category, city, gender, price, original_price, image, secondary_image, badge, origin, fabric, sizes, description, is_new, is_sale, is_thrift, is_pretoria, condition, measurements, rarity, stock, stock_per_size, status)
VALUES (102, 'Urban Soul Heavyweight Twill Cargo Pant', 'Urban Soul', 'urban-soul', 'workwear', 'Pretoria', '{"UNISEX"}', 849, NULL, 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=900&q=80', 'PRETORIA CUT', 'Pretoria, South Africa', 'Heavyweight 320 GSM Ripstop Cotton Twill, Gusseted Pockets', '{"30","32","34","36"}', 'Structured utility trousers with custom hardware and articulated knee darting.', true, false, false, true, NULL, NULL, NULL, 68, '{"30":14,"32":26,"34":20,"36":8}'::jsonb, 'active')
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price, stock = EXCLUDED.stock, status = EXCLUDED.status;
INSERT INTO public.products (id, title, brand, brand_slug, category, city, gender, price, original_price, image, secondary_image, badge, origin, fabric, sizes, description, is_new, is_sale, is_thrift, is_pretoria, condition, measurements, rarity, stock, stock_per_size, status)
VALUES (103, 'Urban Soul Boxy Capital Heritage Tee', 'Urban Soul', 'urban-soul', 'pretoria', 'Pretoria', '{"UNISEX"}', 449, NULL, 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80', 'CORE ESSENTIAL', 'Pretoria, South Africa', '260 GSM Combed Ring-Spun Cotton, Blind Hem Stitching', '{"S","M","L","XL"}', 'Relaxed crewneck tee cut with high collar ribbing and garment-dyed wash.', false, false, false, true, NULL, NULL, NULL, 44, '{"S":8,"M":16,"L":14,"XL":6}'::jsonb, 'active')
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price, stock = EXCLUDED.stock, status = EXCLUDED.status;
INSERT INTO public.products (id, title, brand, brand_slug, category, city, gender, price, original_price, image, secondary_image, badge, origin, fabric, sizes, description, is_new, is_sale, is_thrift, is_pretoria, condition, measurements, rarity, stock, stock_per_size, status)
VALUES (104, 'Urban Soul 012 Embroidered Graphic Cap', 'Urban Soul', 'urban-soul', 'accessories', 'Pretoria', '{"UNISEX"}', 320, NULL, 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1534215754734-18e55d13e346?auto=format&fit=crop&w=900&q=80', 'LOW STOCK', 'Pretoria, South Africa', '6-Panel Unstructured Heavy Cotton Chino Twill, Brass Buckle', '{"One Size"}', 'Low profile dad cap with raised embroidery commemorating Pretoria streetwear roots.', false, false, false, true, NULL, NULL, NULL, 14, '{"One Size":14}'::jsonb, 'active')
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price, stock = EXCLUDED.stock, status = EXCLUDED.status;

-- 4. INITIAL VENDOR ORDERS
INSERT INTO public.orders (order_number, customer_name, customer_city, locker_station, total_amount, commission_amount, payout_amount, status, waybill_number, brand_slug)
VALUES ('LB-84920', 'Thabo Molefe', 'Pretoria', 'Hatfield Plaza Smart Locker (012)', 620, 80.6, 539.4, 'pending_pack', 'BG-84920-PTA', 'lesupa-atelier')
ON CONFLICT (order_number) DO NOTHING;
INSERT INTO public.orders (order_number, customer_name, customer_city, locker_station, total_amount, commission_amount, payout_amount, status, waybill_number, brand_slug)
VALUES ('LB-84881', 'Kagiso Dlamini', 'Johannesburg', 'Braamfontein Juta Smart Locker', 1450, 188.5, 1261.5, 'dispatched_to_locker', 'BG-84881-JHB', 'mokasi')
ON CONFLICT (order_number) DO NOTHING;
INSERT INTO public.orders (order_number, customer_name, customer_city, locker_station, total_amount, commission_amount, payout_amount, status, waybill_number, brand_slug)
VALUES ('LB-84732', 'Nandi Khumalo', 'Pretoria', 'Hatfield Plaza Smart Locker (012)', 450, 58.5, 391.5, 'in_transit', 'BG-84732-PTA', 'lesupa-atelier')
ON CONFLICT (order_number) DO NOTHING;

-- Reset identity sequences
SELECT setval('public.products_id_seq', (SELECT MAX(id) FROM public.products));
SELECT setval('public.vendors_id_seq', (SELECT MAX(id) FROM public.vendors));
